### ISSUE TITLE
Flans addon

### ISSUE THREAD

**Issue by DatDopeBro** [CrazyWolf23/FlansAutomobileAddon#1]
Wow!!! Can't wait for the addon,keep up the good work!!!

**Comment by CrazyWolf23** [comment]
@DatDopeBro Thanks for the support! :+1:

**Comment by CrazyWolf23** [comment]
@DatDopeBro Is there any automobiles you want added first?

**Comment by DatDopeBro** [comment]
Wow thanks!!! If it's not a problem,can you add a jeep and a simple car? I don't require much as long as there's cars in mcpe it would be AWESOME!!!

**Comment by CrazyWolf23** [comment]
Actually,  there is a ModPE script that has a car, but its very bugy. Just search car mech mod

**Comment by DatDopeBro** [comment]
Yeah i know,but as you say it's very buggy so i didn't like that mod very much...

**Comment by DatDopeBro** [comment]
Are u gonna make the addon?

**Comment by CrazyWolf23** [comment]
@DatDopeBro yes, this is like a addon that is secondary, I'm helping another group right now, I'll work on this tomorrow for sure.

**Comment by DatDopeBro** [comment]
You're helping MrCrayfish right?

**Comment by DatDopeBro** [comment]
Yeah i can't wait for the furniture mod too!!!

**Comment by CrazyWolf23** [comment]
I'm not doing anything for mr crayfish right now, but I'm helping with another big addon.

**Comment by DatDopeBro** [comment]
What is the addon?

**Comment by DatDopeBro** [comment]
Are you gonna make this addon or what?

**Comment by CrazyWolf23** [comment]
I'm still a noob with addons I'm just testing with entity's so it'll be a little bit till it is in process.

**Comment by CrazyWolf23** [comment]
@DatDopeBro And the addon is PE like PC addon, were porting pc to pe.

**Comment by DatDopeBro** [comment]
Ok,hope you could make it awesome!!!

**Comment by Koolman12** [comment]
Dude i told him to make this addon me And @CrazyWolf23 are buds :-P

**Comment by CrazyWolf23** [comment]
Hey @Koolman12  can you tell me the list of items, blocks, and automobiles in the actual mod from pc please. That will help me out alot.

**Comment by Koolman12** [comment]
Corvett jeep helicopter plane tank army jeep army helicoper lambo buggotti turrent dodge viper and camero and a Farrari and a mercades
